// Command fixture builds a self-contained fake home from demo/data.json, so the
// picker can be demoed (and recorded) against synthetic sessions instead of a
// real machine's history.
//
// Everything lands under demo/.fixture/home (gitignored), laid out exactly
// where AgentBridge looks by default. Running the demo is then just HOME=<that>, with
// no path overrides and nothing pointing back at the real machine:
//
//	.local/share/opencode/opencode.db   OpenCode's session store
//	.claude-cc1/projects/...            Claude account "cc1"
//	.claude-cc2/projects/...            Claude account "cc2"
//	.codex-cx1/sessions/...             Codex account "cx1"
//	.codex-cx2/sessions/...             Codex account "cx2"
//	.config/agentbridge/config.json     AgentBridge config naming every account
//
// Entries with "machine": "desk" go to a second home, demo/.fixture/desk, which
// stands in for another machine: the demos browse it (Ctrl+R), pull from it and
// push to it through AGB_DEMO_REMOTES=desk=<that dir>. Its sessions name their
// directories as this home would, since a real second machine of the same user
// has the same home path. It gets stub claude, codex and herdr commands and a
// link to bin/agb, so its "agb --print --json" answers like a real machine's.
//
// The home path is built from the repository's demo/ directory rather than
// read from $HOME, so this can never write into a real home directory.
//
// Run from the repository root: go run ./demo/fixture
package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

// entry is one synthetic session. Nothing in data.json is real: the projects,
// prompts and replies are invented so the recording can be regenerated by
// anyone. Ago is minutes before "now" at build time. Tool is "opencode" or an
// account name. Codex stores no title, so a Codex row is titled by its opening
// prompt and Title is only a label for whoever edits the file.
type entry struct {
	Tool    string      `json:"tool"`
	Machine string      `json:"machine,omitempty"`
	Ago     int         `json:"ago"`
	Dir     string      `json:"dir"`
	Title   string      `json:"title"`
	Turns   [][2]string `json:"turns"`

	index     int
	directory string
	updatedAt time.Time
}

type account struct {
	Name      string `json:"name"`
	ConfigDir string `json:"configDir,omitempty"`
	CodexHome string `json:"codexHome,omitempty"`
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func writeFile(path string, contents string, modTime time.Time) {
	must(os.MkdirAll(filepath.Dir(path), 0o755))
	must(os.WriteFile(path, []byte(contents), 0o644))
	// The Claude and Codex readers take updatedAt from the file's mtime.
	if !modTime.IsZero() {
		must(os.Chtimes(path, modTime, modTime))
	}
}

func writeConfig(home string, config obj) {
	data, err := json.MarshalIndent(config, "", "  ")
	must(err)
	writeFile(filepath.Join(home, ".config", "agentbridge", "config.json"), string(data)+"\n", time.Time{})
}

func writeStub(path, body string) {
	writeFile(path, "#!/bin/sh\n"+body+"\n", time.Time{})
	must(os.Chmod(path, 0o755))
}

func jsonLine(value any) string {
	data, err := json.Marshal(value)
	must(err)
	return string(data)
}

type obj = map[string]any

// Stable ids: the same session always gets the same id, so re-running the
// build produces a diff-free fixture apart from timestamps.
func opencodeID(index int) string { return fmt.Sprintf("ses_demo%02d", index+1) }
func claudeID(index int) string {
	return fmt.Sprintf("9f2c%04x-4d1a-4c7e-b8f3-%012d", index+1, index+1)
}
func codexID(index int) string {
	return fmt.Sprintf("4b7e%04x-8c2d-4f1b-a903-%012d", index+1, index+1)
}

func buildOpencodeDB(entries []*entry, path string) {
	must(os.MkdirAll(filepath.Dir(path), 0o755))
	db, err := sql.Open("sqlite", path)
	must(err)
	defer db.Close()

	// Only the columns AgentBridge actually reads; the real schema is much wider.
	_, err = db.Exec(`
		create table session (
			id text primary key, project_id text not null, directory text not null,
			title text not null, time_created integer not null,
			time_updated integer not null, time_archived integer);
		create table message (
			id text primary key, session_id text not null,
			time_created integer not null, data text not null);
		create table part (
			id text primary key, message_id text not null, session_id text not null,
			time_created integer not null, data text not null);`)
	must(err)

	tx, err := db.Begin()
	must(err)
	for _, e := range entries {
		id := opencodeID(e.index)
		started := e.updatedAt.Add(-time.Duration(len(e.Turns)) * time.Minute)
		_, err := tx.Exec(`insert into session values (?, ?, ?, ?, ?, ?, null)`,
			id, "prj_"+filepath.Base(e.directory), e.directory, e.Title, started.UnixMilli(), e.updatedAt.UnixMilli())
		must(err)

		for i, turn := range e.Turns {
			messageID := fmt.Sprintf("msg_%s_%d", id, i)
			created := started.Add(time.Duration(i) * time.Minute).UnixMilli()
			_, err := tx.Exec(`insert into message values (?, ?, ?, ?)`,
				messageID, id, created, jsonLine(obj{"role": turn[0]}))
			must(err)
			_, err = tx.Exec(`insert into part values (?, ?, ?, ?, ?)`,
				"prt_"+messageID, messageID, id, created, jsonLine(obj{"type": "text", "text": turn[1]}))
			must(err)
		}
	}
	must(tx.Commit())
}

func buildClaudeAccount(entries []*entry, configDir string) {
	for _, e := range entries {
		lines := []string{jsonLine(obj{"type": "ai-title", "aiTitle": e.Title})}
		for _, turn := range e.Turns {
			lines = append(lines, jsonLine(obj{
				"type":    turn[0],
				"cwd":     e.directory,
				"message": obj{"role": turn[0], "content": []any{obj{"type": "text", "text": turn[1]}}},
			}))
		}
		// Claude Code names a project directory after the cwd, with every
		// separator turned into a dash.
		project := strings.ReplaceAll(e.directory, "/", "-")
		path := filepath.Join(configDir, "projects", project, claudeID(e.index)+".jsonl")
		writeFile(path, strings.Join(lines, "\n")+"\n", e.updatedAt)
	}
}

// Codex files rollouts under sessions/YYYY/MM/DD, one JSONL per session: a
// session_meta line, then one response_item per turn.
func buildCodexAccount(entries []*entry, home string) {
	for _, e := range entries {
		id := codexID(e.index)
		started := e.updatedAt.Add(-time.Duration(len(e.Turns)) * time.Minute).UTC()
		stamp := started.Format("2006-01-02T15:04:05.000Z")

		lines := []string{jsonLine(obj{
			"timestamp": stamp,
			"type":      "session_meta",
			"payload":   obj{"id": id, "timestamp": stamp, "cwd": e.directory, "cli_version": "0.154.0"},
		})}
		for _, turn := range e.Turns {
			kind := "output_text"
			if turn[0] == "user" {
				kind = "input_text"
			}
			lines = append(lines, jsonLine(obj{
				"timestamp": stamp,
				"type":      "response_item",
				"payload":   obj{"type": "message", "role": turn[0], "content": []any{obj{"type": kind, "text": turn[1]}}},
			}))
		}

		name := fmt.Sprintf("rollout-%s-%s.jsonl", started.Format("2006-01-02T15-04-05"), id)
		path := filepath.Join(home, "sessions", started.Format("2006"), started.Format("01"), started.Format("02"), name)
		writeFile(path, strings.Join(lines, "\n")+"\n", e.updatedAt)
	}
}

func main() {
	demoDir, err := filepath.Abs("demo")
	must(err)
	if _, err := os.Stat(filepath.Join(demoDir, "data.json")); err != nil {
		must(fmt.Errorf("run from the repository root: %w", err))
	}
	home := filepath.Join(demoDir, ".fixture", "home")
	desk := filepath.Join(demoDir, ".fixture", "desk")
	onDesk := func(path string) string { return desk + strings.TrimPrefix(path, home) }

	claudeAccounts := []account{
		{Name: "cc1", ConfigDir: filepath.Join(home, ".claude-cc1")},
		{Name: "cc2", ConfigDir: filepath.Join(home, ".claude-cc2")},
	}
	codexAccounts := []account{
		{Name: "cx1", CodexHome: filepath.Join(home, ".codex-cx1")},
		{Name: "cx2", CodexHome: filepath.Join(home, ".codex-cx2")},
	}

	raw, err := os.ReadFile(filepath.Join(demoDir, "data.json"))
	must(err)
	var entries []*entry
	must(json.Unmarshal(raw, &entries))

	now := time.Now()
	byTool := map[string][]*entry{}
	deskByTool := map[string][]*entry{}
	for i, e := range entries {
		e.index = i
		e.directory = e.Dir
		if strings.HasPrefix(e.Dir, "~/") {
			e.directory = filepath.Join(home, e.Dir[2:])
		}
		e.updatedAt = now.Add(-time.Duration(e.Ago) * time.Minute)
		if e.Machine == "desk" {
			deskByTool[e.Tool] = append(deskByTool[e.Tool], e)
		} else {
			byTool[e.Tool] = append(byTool[e.Tool], e)
		}
	}

	must(os.RemoveAll(home))
	must(os.RemoveAll(desk))
	must(os.MkdirAll(home, 0o755))

	// The picker refuses to open a session whose recorded cwd has gone, and a
	// push or pull needs the project on both sides, so every project directory
	// exists on both machines even though they stay empty.
	for _, e := range entries {
		must(os.MkdirAll(e.directory, 0o755))
		must(os.MkdirAll(onDesk(e.directory), 0o755))
	}

	buildOpencodeDB(byTool["opencode"], filepath.Join(home, ".local", "share", "opencode", "opencode.db"))
	var deskClaude, deskCodex []account
	for _, a := range claudeAccounts {
		buildClaudeAccount(byTool[a.Name], a.ConfigDir)
		buildClaudeAccount(deskByTool[a.Name], onDesk(a.ConfigDir))
		deskClaude = append(deskClaude, account{Name: a.Name, ConfigDir: onDesk(a.ConfigDir)})
	}
	for _, a := range codexAccounts {
		buildCodexAccount(byTool[a.Name], a.CodexHome)
		buildCodexAccount(deskByTool[a.Name], onDesk(a.CodexHome))
		deskCodex = append(deskCodex, account{Name: a.Name, CodexHome: onDesk(a.CodexHome)})
	}

	// The arrive hook opens a pushed session in a herdr tab on desk, as a real
	// setup would; desk's herdr is a stub that answers like one.
	writeConfig(home, obj{
		"skipPermissions":      false,
		"claudeAccounts":       claudeAccounts,
		"defaultClaudeAccount": "cc1",
		"codexAccounts":        codexAccounts,
		"defaultCodexAccount":  "cx1",
		"moveHosts":            []string{"desk"},
		"arrive": obj{
			"desk": `p=$(herdr tab create --label {title} --cwd {dir} --no-focus | jq -r .result.root_pane.pane_id) && herdr pane run "$p" {resume}`,
		},
	})
	writeConfig(desk, obj{
		"claudeAccounts":       deskClaude,
		"defaultClaudeAccount": "cc1",
		"codexAccounts":        deskCodex,
		"defaultCodexAccount":  "cx1",
	})

	// Both machines can resume (a push or pull checks for the tool), and desk's
	// accounts are logged in.
	for _, dir := range []string{home, desk} {
		writeStub(filepath.Join(dir, ".local", "bin", "claude"), "exit 0")
		writeStub(filepath.Join(dir, ".local", "bin", "codex"), "exit 0")
	}
	writeStub(filepath.Join(desk, ".local", "bin", "herdr"), `case "$1 $2" in
  "tab create") echo '{"result":{"root_pane":{"pane_id":"w1:p2"}}}' ;;
esac`)
	must(os.Symlink(filepath.Join(filepath.Dir(demoDir), "bin", "agb"), filepath.Join(desk, ".local", "bin", "agb")))
	for _, a := range deskClaude {
		writeFile(filepath.Join(a.ConfigDir, ".credentials.json"), "{}\n", time.Time{})
	}
	for _, a := range deskCodex {
		writeFile(filepath.Join(a.CodexHome, "auth.json"), "{}\n", time.Time{})
	}

	var counts []string
	for _, tool := range []string{"opencode", "cc1", "cc2", "cx1", "cx2"} {
		counts = append(counts, fmt.Sprintf("%s=%d", tool, len(byTool[tool])))
	}
	deskCount := 0
	for _, list := range deskByTool {
		deskCount += len(list)
	}
	counts = append(counts, fmt.Sprintf("desk=%d", deskCount))
	cwd, _ := os.Getwd()
	relative, err := filepath.Rel(cwd, home)
	if err != nil {
		relative = home
	}
	fmt.Printf("Fixture home built at %s (%s)\n", relative, strings.Join(counts, " "))
}
